name: PlumeESXv1
version: v1.0.0-rc1
author: Tabarra & Chip
description: A full featured (13 jobs) and highly configurable yet lightweight ESX v1.2 base that can be easily extendable. 

variables:
  dbHost: localhost
  dbUsername: root
  dbPassword: ""
  # dbName: dep_keep
  # dbOverwrite: yes_delete_existing_database

tasks:
  # Download and prepare server.cfg
  - action: download_file
    url: https://gist.githubusercontent.com/tabarra/b585c7aaed1ed93a704ff160e8ad2bef/raw/62966e7be199b119bbe35236af59e0887172ed36/server.cfg
    path: ./server.cfg

  # Prepare database
  - action: download_file
    url: https://gist.githubusercontent.com/tabarra/13dc11a594f2e5e0e94d32b08836566c/raw/ea5e46e5777a50a15735d3ddacd56efdcb10a1b8/esx1v2.sql
    path: ./esx1v2.sql
    
  - action: connect_database
  # - action: query_database
  #   query: |
  #     DROP DATABASE `dep_keep`;
  #     CREATE DATABASE `dep_keep` /*!40100 COLLATE 'utf8_general_ci' */;
  #     USE `dep_keep`;
  - action: query_database
    file: ./esx1v2.sql

  # Download default CFX resources
  - action: download_github
    src: https://github.com/citizenfx/cfx-server-data
    ref: 6eaa3525a6858a83546dc9c4ce621e59eae7085c
    subpath: resources
    dest: ./resources

  # Download basic resources and ESX dependencies
  - action: download_github
    src: https://github.com/Blumlaut/EasyAdmin
    dest: ./resources/EasyAdmin

  - action: download_github
    src: https://github.com/esx-framework/async
    dest: ./resources/async

  - action: download_github
    src: https://github.com/brouznouf/fivem-mysql-async
    dest: ./resources/mysql-async

  - action: download_github
    src: https://github.com/esx-framework/cron
    dest: ./resources/cron

  - action: download_github
    src: https://github.com/esx-framework/skinchanger
    dest: ./resources/skinchanger

  - action: download_github
    src: https://github.com/HypeLevels/simpledrift
    ref: v1.1
    dest: ./resources/simpledrift

  - action: download_github
    src: https://github.com/dsheedes/cd_easytime
    ref: aaff63bf6215c8573aef0adf9deaa5746f3884b6
    dest: ./resources/cd_easytime

  # Download ESX resources
  - action: download_github
    src: https://github.com/esx-framework/es_extended
    ref: legacy
    dest: ./resources/[esx]/es_extended

  - action: download_github
    src: https://github.com/esx-framework/esx_menu_default
    dest: ./resources/[esx]/esx_menu_default

  - action: download_github
    src: https://github.com/esx-framework/esx_menu_dialog
    dest: ./resources/[esx]/esx_menu_dialog

  - action: download_github
    src: https://github.com/esx-framework/esx_menu_list
    dest: ./resources/[esx]/esx_menu_list

  - action: download_github
    src: https://github.com/esx-framework/esx_datastore
    dest: ./resources/[esx]/esx_datastore

  - action: download_github
    src: https://github.com/esx-framework/esx_identity
    dest: ./resources/[esx]/esx_identity

  - action: download_github
    src: https://github.com/esx-framework/esx_skin
    dest: ./resources/[esx]/esx_skin

  - action: download_github
    src: https://github.com/esx-framework/esx_status
    dest: ./resources/[esx]/esx_status

  - action: download_github
    src: https://github.com/esx-framework/esx_basicneeds
    dest: ./resources/[esx]/esx_basicneeds

  - action: download_github
    src: https://github.com/esx-framework/esx_billing
    dest: ./resources/[esx]/esx_billing

  - action: download_github
    src: https://github.com/esx-framework/esx_addoninventory
    dest: ./resources/[esx]/esx_addoninventory

  - action: download_github
    src: https://github.com/esx-framework/esx_addonaccount
    dest: ./resources/[esx]/esx_addonaccount

  - action: download_github
    src: https://github.com/esx-framework/esx_society
    dest: ./resources/[esx]/esx_society

  - action: download_github
    src: https://github.com/esx-framework/esx_license
    dest: ./resources/[esx]/esx_license

  - action: download_github
    src: https://github.com/esx-framework/esx_service
    dest: ./resources/[esx]/esx_service

  - action: download_github
    src: https://github.com/esx-framework/esx_garage
    dest: ./resources/[esx]/esx_garage

  - action: download_github
    src: https://github.com/esx-framework/esx_vehicleshop
    dest: ./resources/[esx]/esx_vehicleshop

  - action: download_github
    src: https://github.com/esx-framework/esx_jobs
    dest: ./resources/[esx]/esx_jobs

  - action: download_github
    src: https://github.com/esx-framework/esx_joblisting
    dest: ./resources/[esx]/esx_joblisting

  - action: download_github
    src: https://github.com/esx-framework/esx_policejob
    dest: ./resources/[esx]/esx_policejob

  - action: download_github
    src: https://github.com/esx-framework/esx_ambulancejob
    dest: ./resources/[esx]/esx_ambulancejob

  - action: download_github
    src: https://github.com/esx-framework/esx_mechanicjob
    dest: ./resources/[esx]/esx_mechanicjob

  - action: download_github
    src: https://github.com/esx-framework/esx_taxijob
    dest: ./resources/[esx]/esx_taxijob

  - action: download_github
    src: https://github.com/esx-framework/esx_lscustom
    dest: ./resources/[esx]/esx_lscustom

  - action: download_github
    src: https://github.com/esx-framework/esx_shops
    dest: ./resources/[esx]/esx_shops

  - action: download_github
    src: https://github.com/esx-framework/esx_weaponshop
    dest: ./resources/[esx]/esx_weaponshop

  - action: download_github
    src: https://github.com/esx-framework/esx_clotheshop
    dest: ./resources/[esx]/esx_clotheshop

  - action: download_github
    src: https://github.com/esx-framework/esx_barbershop
    dest: ./resources/[esx]/esx_barbershop

  - action: download_github
    src: https://github.com/esx-framework/esx_drugs
    dest: ./resources/[esx]/esx_drugs

  - action: download_github
    src: https://github.com/esx-framework/esx_holdup
    dest: ./resources/[esx]/esx_holdup


