$engine: 2
name: PlumeESX
version: v1.0.0-rc2
author: Tabarra & Chip
description: A full featured (13 jobs) and highly configurable yet lightweight ESX v1.2 base that can be easily extendable. 

tasks:
  # Download and prepare server.cfg / loadingscreen / database
  - action: download_file
    url: https://github.com/tabarra/txAdmin-recipes/archive/main.zip
    path: ./tmp/recipes.zip
  - action: unzip
    src: ./tmp/recipes.zip
    dest: ./tmp

  - action: move_path
    src: ./tmp/plume_esx/server.cfg
    dest: ./server.cfg
  
  - action: move_path
    src: ./tmp/plume_esx/loadingscreen
    dest: ./resources/loadingscreen

  - action: connect_database
  - action: query_database
    file: ./tmp/plume_esx/plume.sql

  # Download default CFX resources
  - action: download_github
    src: https://github.com/citizenfx/cfx-server-data
    ref: 6eaa3525a6858a83546dc9c4ce621e59eae7085c
    subpath: resources
    dest: ./resources

  # Download basic resources and ESX dependencies
  - action: download_github
    src: https://github.com/Blumlaut/EasyAdmin
    dest: ./resources/EasyAdmin

  - action: download_github
    src: https://github.com/esx-framework/async
    dest: ./resources/async

  - action: download_github
    src: https://github.com/brouznouf/fivem-mysql-async
    dest: ./resources/mysql-async

  - action: download_github
    src: https://github.com/esx-framework/cron
    dest: ./resources/cron

  - action: download_github
    src: https://github.com/esx-framework/skinchanger
    dest: ./resources/skinchanger

  - action: download_github
    src: https://github.com/HypeLevels/simpledrift
    ref: 77e378a2b59fcaca7624cb51575b2a3d39e3b635
    dest: ./resources/simpledrift

  - action: download_github
    src: https://github.com/dsheedes/cd_easytime
    ref: aaff63bf6215c8573aef0adf9deaa5746f3884b6
    dest: ./resources/cd_easytime

  - action: download_github
    src: https://github.com/Bob74/bob74_ipl
    ref: ed6af93e1850d7f749a9aee42042d1243c6d00fd
    dest: ./resources/bob74_ipl

  # Download ESX resources
  - action: download_github
    src: https://github.com/esx-framework/es_extended
    ref: legacy
    dest: ./resources/[esx]/es_extended

  - action: download_github
    src: https://github.com/esx-framework/esx_menu_default
    dest: ./resources/[esx]/esx_menu_default

  - action: download_github
    src: https://github.com/esx-framework/esx_menu_dialog
    dest: ./resources/[esx]/esx_menu_dialog

  - action: download_github
    src: https://github.com/esx-framework/esx_menu_list
    dest: ./resources/[esx]/esx_menu_list

  - action: download_github
    src: https://github.com/esx-framework/esx_datastore
    dest: ./resources/[esx]/esx_datastore

  - action: download_github
    src: https://github.com/esx-framework/esx_identity
    dest: ./resources/[esx]/esx_identity

  - action: download_github
    src: https://github.com/esx-framework/esx_skin
    dest: ./resources/[esx]/esx_skin

  - action: download_github
    src: https://github.com/esx-framework/esx_status
    dest: ./resources/[esx]/esx_status

  - action: download_github
    src: https://github.com/esx-framework/esx_basicneeds
    dest: ./resources/[esx]/esx_basicneeds

  - action: download_github
    src: https://github.com/esx-framework/esx_billing
    dest: ./resources/[esx]/esx_billing

  - action: download_github
    src: https://github.com/esx-framework/esx_addoninventory
    dest: ./resources/[esx]/esx_addoninventory

  - action: download_github
    src: https://github.com/esx-framework/esx_addonaccount
    dest: ./resources/[esx]/esx_addonaccount

  - action: download_github
    src: https://github.com/esx-framework/esx_society
    dest: ./resources/[esx]/esx_society

  - action: download_github
    src: https://github.com/esx-framework/esx_license
    dest: ./resources/[esx]/esx_license

  - action: download_github
    src: https://github.com/esx-framework/esx_service
    dest: ./resources/[esx]/esx_service

  - action: download_github
    src: https://github.com/esx-framework/esx_garage
    dest: ./resources/[esx]/esx_garage

  - action: download_github
    src: https://github.com/esx-framework/esx_vehicleshop
    dest: ./resources/[esx]/esx_vehicleshop

  - action: download_github
    src: https://github.com/esx-framework/esx_jobs
    dest: ./resources/[esx]/esx_jobs

  - action: download_github
    src: https://github.com/esx-framework/esx_joblisting
    dest: ./resources/[esx]/esx_joblisting

  - action: download_github
    src: https://github.com/esx-framework/esx_policejob
    dest: ./resources/[esx]/esx_policejob

  - action: download_github
    src: https://github.com/esx-framework/esx_ambulancejob
    dest: ./resources/[esx]/esx_ambulancejob

  - action: download_github
    src: https://github.com/esx-framework/esx_mechanicjob
    dest: ./resources/[esx]/esx_mechanicjob

  - action: download_github
    src: https://github.com/esx-framework/esx_taxijob
    dest: ./resources/[esx]/esx_taxijob

  - action: download_github
    src: https://github.com/esx-framework/esx_lscustom
    dest: ./resources/[esx]/esx_lscustom

  - action: download_github
    src: https://github.com/esx-framework/esx_shops
    dest: ./resources/[esx]/esx_shops

  - action: download_github
    src: https://github.com/esx-framework/esx_weaponshop
    dest: ./resources/[esx]/esx_weaponshop

  - action: download_github
    src: https://github.com/esx-framework/esx_clotheshop
    dest: ./resources/[esx]/esx_clotheshop

  - action: download_github
    src: https://github.com/esx-framework/esx_barbershop
    dest: ./resources/[esx]/esx_barbershop

  - action: download_github
    src: https://github.com/esx-framework/esx_drugs
    dest: ./resources/[esx]/esx_drugs

  - action: download_github
    src: https://github.com/esx-framework/esx_holdup
    dest: ./resources/[esx]/esx_holdup

  ## GCPhone stuff
  - action: download_file
    url: https://github.com/Re-Ignited-Development/Re-Ignited-Phone/releases/download/V1.4/resources-1.2.zip
    path: ./tmp/gcphone.zip
  - action: unzip
    src: ./tmp/gcphone.zip
    dest: ./tmp
  - action: move_path
    src: ./tmp/resources-1.2/gcphone
    dest: ./resources/gcphone
    # FIXME: move to the github plume folder
  - action: download_file
    url: https://gist.githubusercontent.com/tabarra/3d41d03ec701c1de9c1d70b9b5554a96/raw/59fbc15ba42e5356624227aa309b11d5f3b73573/gcphone.sql
    path: ./tmp/gcphone.sql
  - action: query_database
    file: ./tmp/gcphone.sql
  

  ## KL HUD v2
  - action: download_github
    src: https://github.com/Kilichi/Kl_HudV2
    ref: ac8a321ff335706509bdc6122a2984a80082e669
    dest: ./resources/Kl_HudV2

  - action: replace_string
    file: ./resources/[esx]/esx_status/client/main.lua
    search: 'esx_status:onTick'
    replace: 'Kl_Hud:onTick'


  ## Final touches
  - action: replace_string
    mode: all_vars
    file: 
      - ./server.cfg
      - ./resources/loadingscreen/config.js
    
  - action: remove_path
    path: ./tmp

to_add: |
  https://forum.cfx.re/t/esx-v1-exm-esx-adminplus/1202550 (something like this)

