$engine: 2
$onesync: on
name: CFX Default
version: 2.0.0
author: Tabarra
description: |-
    Recipe for the base resources required to run a server.

tasks: 
  # Download default CFX resources
  - action: download_github
    src: https://github.com/citizenfx/cfx-server-data
    ref: 88f4f974b855e0bf2ca5f51b9916648bd5b7d44b
    subpath: resources
    dest: ./resources

  - action: download_file
    url: https://raw.githubusercontent.com/tabarra/txAdmin-recipes/main/cfx_default/server.cfg
    path: ./server.cfg
